[package]
name = "aero-devices-input"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-io-snapshot = { path = "../aero-io-snapshot" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
