[package]
name = "aero-tests"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition.workspace = true

[dependencies]
aero_cpu_core = { path = "../aero_cpu_core" }
aero_x86 = { path = "../aero_x86" }
iced-x86.workspace = true

[dev-dependencies]
proptest = "1.4.0"
