[package]
name = "aero-cpu"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-core = { path = "../aero-core" }
aero-jit-proto = { path = "../aero-jit-proto" }
iced-x86.workspace = true
thiserror.workspace = true
[dev-dependencies]
