[package]
name = "aero-net-stack"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
nt-packetlib = { path = "../nt-packetlib" }
aero-io-snapshot = { path = "../aero-io-snapshot" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
futures-util = "0.3"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = "0.26"
