[package]
name = "aero-opfs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
# Enables shared-memory/threads-related helpers on wasm32 (e.g. using atomic counters so `Send`
# wrappers can enforce thread affinity deterministically). This is intended to be driven by build
# system features (see `aero-wasm`'s `wasm-threaded` feature).
wasm-threaded = []

[dependencies]
aero-storage = { path = "../aero-storage" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
st-idb = { path = "../st-idb" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Blob", "DomException", "File", "WorkerGlobalScope", "console"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
aero-snapshot = { path = "../aero-snapshot" }
