[package]
name = "aero-machine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-cpu-core = { path = "../aero-cpu-core" }
aero-devices = { path = "../devices" }
aero-platform = { path = "../platform" }
firmware = { path = "../firmware" }
machine = { path = "../machine" }
memory = { path = "../memory" }

[dev-dependencies]
pretty_assertions = "1"
