[package]
name = "aero-machine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-cpu-core = { path = "../aero-cpu-core" }
aero-devices = { path = "../devices" }
aero-devices-input = { path = "../aero-devices-input" }
aero-mmu = { path = "../aero-mmu" }
aero-net-backend = { path = "../aero-net-backend" }
aero-platform = { path = "../platform" }
aero-snapshot = { path = "../aero-snapshot", features = ["io-snapshot"] }
firmware = { path = "../firmware" }
memory = { path = "../memory" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
aero-ipc = { path = "../aero-ipc" }
aero-pc-platform = { path = "../aero-pc-platform" }

[dev-dependencies]
pretty_assertions = "1"
aero-storage = { path = "../aero-storage" }
