[package]
name = "aero-platform"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-cpu-core = { path = "../aero-cpu-core" }
aero-interrupts = { path = "../aero-interrupts" }
aero-io-snapshot = { path = "../aero-io-snapshot" }
aero-mmu = { path = "../aero-mmu" }
aero-pc-constants = { path = "../aero-pc-constants" }
memory = { path = "../memory" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
criterion = { version = "0.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[features]
bench = ["dep:criterion"]

[dev-dependencies]
aero-devices = { path = "../devices" }
aero-acpi = { path = "../aero-acpi" }
firmware = { path = "../firmware" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bench]]
name = "a20_disabled_physical"
harness = false
required-features = ["bench"]
