[package]
name = "aero-platform"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-interrupts = { path = "../aero-interrupts" }
memory = { path = "../memory" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[dev-dependencies]
aero-devices = { path = "../devices" }
aero-acpi = { path = "../aero-acpi" }
