[package]
name = "aero-platform"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-cpu-core = { path = "../aero-cpu-core" }
aero-interrupts = { path = "../aero-interrupts" }
aero-io-snapshot = { path = "../aero-io-snapshot" }
aero-mmu = { path = "../aero-mmu" }
memory = { path = "../memory" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[dev-dependencies]
aero-devices = { package = "devices", path = "../devices" }
aero-acpi = { path = "../aero-acpi" }
firmware = { path = "../firmware" }
