[package]
name = "aero-virtio"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-audio = { path = "../aero-audio" }
aero-io-snapshot = { path = "../aero-io-snapshot" }
aero-net-backend = { path = "../aero-net-backend" }
aero-storage = { path = "../aero-storage" }
nt-packetlib = { path = "../nt-packetlib" }
virtio-gpu-proto = { path = "../virtio-gpu-proto" }

[dev-dependencies]
aero-devices = { path = "../devices" }
