[package]
name = "aero-virtio"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-audio = { path = "../aero-audio" }
virtio-gpu-proto = { path = "../virtio-gpu-proto" }

[dev-dependencies]
aero-devices = { path = "../devices" }
