[package]
name = "aero_jit"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
wasm-encoder = "0.244.0"
thiserror = "2.0.17"
aero_cpu = { path = "../aero_cpu" }
aero_cpu_core = { path = "../aero_cpu_core" }
aero_types = { path = "../aero_types" }
aero_x86 = { path = "../aero_x86" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
aero_cpu_core = { path = "../aero_cpu_core" }
wasmtime = "40.0.1"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3"
wasmparser = "0.244.0"
wasmi = "1.0.7"
