[package]
name = "aero-devices"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-platform = { path = "../platform" }
aero-interrupts = { path = "../aero-interrupts" }
aero-devices-input = { path = "../aero-devices-input" }
aero-io-snapshot = { path = "../aero-io-snapshot" }
memory = { path = "../memory" }

[dev-dependencies]
aero-acpi = { path = "../aero-acpi" }
aero_cpu_core = { path = "../aero_cpu_core" }
aero-snapshot = { path = "../aero-snapshot", features = ["io-snapshot"] }
