[package]
name = "aero-devices"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-platform = { path = "../platform" }
memory = { path = "../memory" }

[dev-dependencies]
aero-acpi = { path = "../aero-acpi" }
