[package]
name = "aero-devices"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-platform = { path = "../platform" }
aero-interrupts = { path = "../aero-interrupts" }
aero-io-snapshot = { path = "../aero-io-snapshot" }
aero-devices-input = { path = "../aero-devices-input" }
aero-storage-adapters = { path = "../aero-storage-adapters" }
memory = { path = "../memory" }

[dev-dependencies]
aero-acpi = { path = "../aero-acpi" }
aero-cpu-core = { path = "../aero-cpu-core" }
aero-snapshot = { path = "../aero-snapshot", features = ["io-snapshot"] }
aero-storage = { path = "../aero-storage" }
serde_json = "1"
