[package]
name = "conformance"
version = "0.1.0"
edition = "2021"

[dependencies]
aero-cpu-decoder = { path = "../aero-cpu-decoder" }
iced-x86 = "1.21.0"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
aero-auth-tokens = { path = "../aero-auth-tokens" }
aero-l2-protocol = { path = "../aero-l2-protocol" }
aero-tcp-mux-protocol = { path = "../aero-tcp-mux-protocol" }
aero-udp-relay-protocol = { path = "../aero-udp-relay-protocol" }
