[package]
name = "aero-win7-slipstream"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.79"
base64 = "0.22.1"
clap = { version = "4.5.1", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sha1 = "0.10.6"
sha2 = "0.10.8"
tempfile = "3.10.1"
walkdir = "2.5.0"
which = "6.0.1"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
