[package]
name = "aero-io-snapshot"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-storage = { path = "../aero-storage" }

[dev-dependencies]
aero-devices-input = { path = "../aero-devices-input" }
