[package]
name = "aero-storage-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
async-stream = "0.3"
axum = "0.7"
bytes = "1"
futures = "0.3"
rand = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["fs", "io-util"] }
tokio-util = { version = "0.7", features = ["io"] }

[dev-dependencies]
http-body-util = "0.1"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread"] }
tower = "0.5"
