[package]
name = "aero-storage-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
thiserror = "1"
tokio = { version = "1", features = ["fs", "io-util"] }

[dev-dependencies]
rand = "0.8"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread"] }

