[package]
name = "aero-net-backend"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# `wasm` feature is enabled so the crate can support `SharedRingBuffer` on wasm32.
aero-ipc = { path = "../aero-ipc", features = ["wasm"] }
