{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aero-gateway.fullname" . }}
  labels:
    {{- include "aero-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "aero-gateway.selectorLabels" . | nindent 6 }}
{{- end }}
