{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aero-gateway.secretName" . }}
  labels:
    {{- include "aero-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.data }}
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
{{- end }}
