[package]
name = "vm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-cpu-core = { path = "../../aero-cpu-core" }
aero-snapshot = { path = "../../aero-snapshot" }
firmware = { path = "../../firmware" }
memory = { path = "../../memory" }

[dev-dependencies]
