[package]
name = "vm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-snapshot = { path = "../aero-snapshot" }
firmware = { path = "../firmware" }
machine = { path = "../machine" }

[dev-dependencies]
aero-cpu-core = { path = "../aero-cpu-core" }
