[package]
name = "aero-webgpu"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
futures-intrusive = "0.5"
thiserror = "1.0"
wgpu = { version = "0.20", features = ["webgl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "OffscreenCanvas"] }

[dev-dependencies]
pollster = "0.3"
