[package]
name = "win-certstore-regblob-export"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.79"
base64 = "0.22.0"
clap = { version = "4.5.1", features = ["derive"] }
pem = "3.0.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Security_Cryptography",
  "Win32_System_Registry",
] }

