[package]
name = "aero-bios"
version = "0.1.0"
edition = "2021"

[dependencies]
aero-acpi = { path = "../aero-acpi" }
firmware-tables = { package = "firmware", path = "../firmware" }

[dev-dependencies]
