[package]
name = "firmware"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-acpi = { path = "../aero-acpi" }
aero-edid = { path = "../aero-edid" }
aero-cpu-core = { path = "../aero-cpu-core" }
aero-pc-constants = { path = "../aero-pc-constants" }
aero-devices = { path = "../devices" }
memory = { path = "../memory" }

[dev-dependencies]
aero-platform = { path = "../platform" }
