[package]
name = "firmware"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-acpi = { path = "../aero-acpi" }
emulator = { path = "../emulator" }
memory = { path = "../memory" }
machine = { path = "../machine" }

[dev-dependencies]
aero-devices = { path = "../devices" }
aero-platform = { path = "../platform" }
