[package]
name = "aero-smp"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-snapshot = { path = "../aero-snapshot" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
firmware = { path = "../firmware" }
