[package]
name = "aero-gpu-trace-replay"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
aero-gpu-trace = { path = "../aero-gpu-trace" }
aero-protocol = { path = "../../emulator/protocol" }
sha2 = "0.10"
